name: Web Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

#      - name: Generate Localization Files
#        id: gen_l10n
#        run: |
#          output=$(flutter gen-l10n)
#          echo "$output"
#
#          if echo "$output" | grep -q "untranslated message"; then
#            echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
#            echo "::error::There are untranslated messages in the following languages:"
#            echo "$output" | grep "untranslated message"
#            echo "::error::Please ensure that all translations are provided in the respective .arb files."
#            exit 1
#          fi
#
#
#
#      - name: Check Localization Content
#        run: |
#          cp lib/l10n/app_localizations.dart /tmp/current.dart
#
#          flutter gen-l10n --suppress-warnings
#
#          dart format .
#
#          if diff -w /tmp/current.dart lib/l10n/app_localizations.dart > /dev/null 2>&1; then
#            echo "âœ“ Localization content is up to date"
#          else
#            echo "::error::Localization content has changed!"
#            echo "Changes detected in app_localizations.dart"
#            echo "Run 'flutter gen-l10n' and 'dart format .' locally, then commit changes."
#            exit 1
#          fi
#
#      - name: Check if translations_utils.dart has changes
#        run: |
#          git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart || (
#            echo "Error: Changes detected in translations_utils.dart. Please run the necessary custom translation utilities and commit changes.";
#            exit 1;
#          )
      - name: Run Dart Format Check
        run: |
          dart format . --set-exit-if-changed || (
            echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
            exit 1;
          )
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4